// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="accel_accel,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=1668,HLS_SYN_TPT=1440,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=10548,HLS_SYN_LUT=15232,HLS_VERSION=2022_1}" *)

module accel (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 512;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [319:0] softmax_weights_i_q0;
wire   [39:0] softmax_weights_t_we0;
wire   [319:0] softmax_weights_t_q0;
wire   [63:0] gmem_softmax_weights;
wire   [63:0] layer_output;
wire   [31:0] label_r;
wire   [63:0] input_error;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    gmem_AWREADY;
wire    gmem_WREADY;
wire    gmem_ARREADY;
wire    gmem_RVALID;
wire   [511:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [8:0] gmem_RFIFONUM;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_start_full_n;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [31:0] entry_proc_U0_label_r_c_din;
wire    entry_proc_U0_label_r_c_write;
wire   [63:0] entry_proc_U0_input_error_c_din;
wire    entry_proc_U0_input_error_c_write;
wire    save_variables_locally_10u_128u_U0_ap_start;
wire    save_variables_locally_10u_128u_U0_ap_done;
wire    save_variables_locally_10u_128u_U0_ap_continue;
wire    save_variables_locally_10u_128u_U0_ap_idle;
wire    save_variables_locally_10u_128u_U0_ap_ready;
wire    save_variables_locally_10u_128u_U0_m_axi_gmem_AWVALID;
wire   [63:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWADDR;
wire   [0:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWID;
wire   [31:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWLEN;
wire   [2:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWSIZE;
wire   [1:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWBURST;
wire   [1:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWLOCK;
wire   [3:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWCACHE;
wire   [2:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWPROT;
wire   [3:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWQOS;
wire   [3:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWREGION;
wire   [0:0] save_variables_locally_10u_128u_U0_m_axi_gmem_AWUSER;
wire    save_variables_locally_10u_128u_U0_m_axi_gmem_WVALID;
wire   [511:0] save_variables_locally_10u_128u_U0_m_axi_gmem_WDATA;
wire   [63:0] save_variables_locally_10u_128u_U0_m_axi_gmem_WSTRB;
wire    save_variables_locally_10u_128u_U0_m_axi_gmem_WLAST;
wire   [0:0] save_variables_locally_10u_128u_U0_m_axi_gmem_WID;
wire   [0:0] save_variables_locally_10u_128u_U0_m_axi_gmem_WUSER;
wire    save_variables_locally_10u_128u_U0_m_axi_gmem_ARVALID;
wire   [63:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARADDR;
wire   [0:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARID;
wire   [31:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARLEN;
wire   [2:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARSIZE;
wire   [1:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARBURST;
wire   [1:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARLOCK;
wire   [3:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARCACHE;
wire   [2:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARPROT;
wire   [3:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARQOS;
wire   [3:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARREGION;
wire   [0:0] save_variables_locally_10u_128u_U0_m_axi_gmem_ARUSER;
wire    save_variables_locally_10u_128u_U0_m_axi_gmem_RREADY;
wire    save_variables_locally_10u_128u_U0_m_axi_gmem_BREADY;
wire   [6:0] save_variables_locally_10u_128u_U0_softmax_weights_address0;
wire    save_variables_locally_10u_128u_U0_softmax_weights_ce0;
wire   [39:0] save_variables_locally_10u_128u_U0_softmax_weights_we0;
wire   [319:0] save_variables_locally_10u_128u_U0_softmax_weights_d0;
wire   [31:0] save_variables_locally_10u_128u_U0_softmax_f_map_stream14_din;
wire    save_variables_locally_10u_128u_U0_softmax_f_map_stream14_write;
wire    sparce_categorical_cross_entropy_10u_U0_ap_start;
wire    sparce_categorical_cross_entropy_10u_U0_ap_done;
wire    sparce_categorical_cross_entropy_10u_U0_ap_continue;
wire    sparce_categorical_cross_entropy_10u_U0_ap_idle;
wire    sparce_categorical_cross_entropy_10u_U0_ap_ready;
wire    sparce_categorical_cross_entropy_10u_U0_softmax_f_map_stream14_read;
wire    sparce_categorical_cross_entropy_10u_U0_label_r_read;
wire   [31:0] sparce_categorical_cross_entropy_10u_U0_softmax_output_error_stream15_din;
wire    sparce_categorical_cross_entropy_10u_U0_softmax_output_error_stream15_write;
wire    softmax_error_propagation_10u_128u_U0_ap_start;
wire    softmax_error_propagation_10u_128u_U0_ap_done;
wire    softmax_error_propagation_10u_128u_U0_ap_continue;
wire    softmax_error_propagation_10u_128u_U0_ap_idle;
wire    softmax_error_propagation_10u_128u_U0_ap_ready;
wire    softmax_error_propagation_10u_128u_U0_softmax_output_error_stream15_read;
wire   [6:0] softmax_error_propagation_10u_128u_U0_weights_address0;
wire    softmax_error_propagation_10u_128u_U0_weights_ce0;
wire   [31:0] softmax_error_propagation_10u_128u_U0_softmax_input_error_stream16_din;
wire    softmax_error_propagation_10u_128u_U0_softmax_input_error_stream16_write;
wire    write_mem_float_128u_U0_ap_start;
wire    write_mem_float_128u_U0_ap_done;
wire    write_mem_float_128u_U0_ap_continue;
wire    write_mem_float_128u_U0_ap_idle;
wire    write_mem_float_128u_U0_ap_ready;
wire    write_mem_float_128u_U0_softmax_input_error_stream16_read;
wire    write_mem_float_128u_U0_m_axi_gmem_AWVALID;
wire   [63:0] write_mem_float_128u_U0_m_axi_gmem_AWADDR;
wire   [0:0] write_mem_float_128u_U0_m_axi_gmem_AWID;
wire   [31:0] write_mem_float_128u_U0_m_axi_gmem_AWLEN;
wire   [2:0] write_mem_float_128u_U0_m_axi_gmem_AWSIZE;
wire   [1:0] write_mem_float_128u_U0_m_axi_gmem_AWBURST;
wire   [1:0] write_mem_float_128u_U0_m_axi_gmem_AWLOCK;
wire   [3:0] write_mem_float_128u_U0_m_axi_gmem_AWCACHE;
wire   [2:0] write_mem_float_128u_U0_m_axi_gmem_AWPROT;
wire   [3:0] write_mem_float_128u_U0_m_axi_gmem_AWQOS;
wire   [3:0] write_mem_float_128u_U0_m_axi_gmem_AWREGION;
wire   [0:0] write_mem_float_128u_U0_m_axi_gmem_AWUSER;
wire    write_mem_float_128u_U0_m_axi_gmem_WVALID;
wire   [511:0] write_mem_float_128u_U0_m_axi_gmem_WDATA;
wire   [63:0] write_mem_float_128u_U0_m_axi_gmem_WSTRB;
wire    write_mem_float_128u_U0_m_axi_gmem_WLAST;
wire   [0:0] write_mem_float_128u_U0_m_axi_gmem_WID;
wire   [0:0] write_mem_float_128u_U0_m_axi_gmem_WUSER;
wire    write_mem_float_128u_U0_m_axi_gmem_ARVALID;
wire   [63:0] write_mem_float_128u_U0_m_axi_gmem_ARADDR;
wire   [0:0] write_mem_float_128u_U0_m_axi_gmem_ARID;
wire   [31:0] write_mem_float_128u_U0_m_axi_gmem_ARLEN;
wire   [2:0] write_mem_float_128u_U0_m_axi_gmem_ARSIZE;
wire   [1:0] write_mem_float_128u_U0_m_axi_gmem_ARBURST;
wire   [1:0] write_mem_float_128u_U0_m_axi_gmem_ARLOCK;
wire   [3:0] write_mem_float_128u_U0_m_axi_gmem_ARCACHE;
wire   [2:0] write_mem_float_128u_U0_m_axi_gmem_ARPROT;
wire   [3:0] write_mem_float_128u_U0_m_axi_gmem_ARQOS;
wire   [3:0] write_mem_float_128u_U0_m_axi_gmem_ARREGION;
wire   [0:0] write_mem_float_128u_U0_m_axi_gmem_ARUSER;
wire    write_mem_float_128u_U0_m_axi_gmem_RREADY;
wire    write_mem_float_128u_U0_m_axi_gmem_BREADY;
wire    write_mem_float_128u_U0_output_r_read;
wire    softmax_weights_i_full_n;
wire    softmax_weights_t_empty_n;
wire    label_r_c_full_n;
wire   [31:0] label_r_c_dout;
wire   [2:0] label_r_c_num_data_valid;
wire   [2:0] label_r_c_fifo_cap;
wire    label_r_c_empty_n;
wire    input_error_c_full_n;
wire   [63:0] input_error_c_dout;
wire   [3:0] input_error_c_num_data_valid;
wire   [3:0] input_error_c_fifo_cap;
wire    input_error_c_empty_n;
wire    softmax_f_map_stream_full_n;
wire   [31:0] softmax_f_map_stream_dout;
wire   [1:0] softmax_f_map_stream_num_data_valid;
wire   [1:0] softmax_f_map_stream_fifo_cap;
wire    softmax_f_map_stream_empty_n;
wire    softmax_output_error_stream_full_n;
wire   [31:0] softmax_output_error_stream_dout;
wire   [3:0] softmax_output_error_stream_num_data_valid;
wire   [3:0] softmax_output_error_stream_fifo_cap;
wire    softmax_output_error_stream_empty_n;
wire    softmax_input_error_stream_full_n;
wire   [31:0] softmax_input_error_stream_dout;
wire   [1:0] softmax_input_error_stream_num_data_valid;
wire   [1:0] softmax_input_error_stream_fifo_cap;
wire    softmax_input_error_stream_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_save_variables_locally_10u_128u_U0_ap_ready;
wire    ap_sync_save_variables_locally_10u_128u_U0_ap_ready;
wire   [0:0] start_for_sparce_categorical_cross_entropy_10u_U0_din;
wire    start_for_sparce_categorical_cross_entropy_10u_U0_full_n;
wire   [0:0] start_for_sparce_categorical_cross_entropy_10u_U0_dout;
wire    start_for_sparce_categorical_cross_entropy_10u_U0_empty_n;
wire   [0:0] start_for_write_mem_float_128u_U0_din;
wire    start_for_write_mem_float_128u_U0_full_n;
wire   [0:0] start_for_write_mem_float_128u_U0_dout;
wire    start_for_write_mem_float_128u_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_save_variables_locally_10u_128u_U0_ap_ready = 1'b0;
end

accel_softmax_weights_RAM_AUTO_1R1W #(
    .DataWidth( 320 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
softmax_weights_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(save_variables_locally_10u_128u_U0_softmax_weights_address0),
    .i_ce0(save_variables_locally_10u_128u_U0_softmax_weights_ce0),
    .i_we0(save_variables_locally_10u_128u_U0_softmax_weights_we0),
    .i_d0(save_variables_locally_10u_128u_U0_softmax_weights_d0),
    .i_q0(softmax_weights_i_q0),
    .t_address0(softmax_error_propagation_10u_128u_U0_weights_address0),
    .t_ce0(softmax_error_propagation_10u_128u_U0_weights_ce0),
    .t_we0(softmax_weights_t_we0),
    .t_d0(320'd0),
    .t_q0(softmax_weights_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(softmax_weights_i_full_n),
    .i_write(save_variables_locally_10u_128u_U0_ap_done),
    .t_empty_n(softmax_weights_t_empty_n),
    .t_read(softmax_error_propagation_10u_128u_U0_ap_ready)
);

accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .gmem_softmax_weights(gmem_softmax_weights),
    .layer_output(layer_output),
    .label_r(label_r),
    .input_error(input_error),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

accel_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_DW( 512 ),
    .USER_AW( 64 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(save_variables_locally_10u_128u_U0_m_axi_gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(save_variables_locally_10u_128u_U0_m_axi_gmem_ARADDR),
    .I_ARLEN(save_variables_locally_10u_128u_U0_m_axi_gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(save_variables_locally_10u_128u_U0_m_axi_gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(write_mem_float_128u_U0_m_axi_gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(write_mem_float_128u_U0_m_axi_gmem_AWADDR),
    .I_AWLEN(write_mem_float_128u_U0_m_axi_gmem_AWLEN),
    .I_WVALID(write_mem_float_128u_U0_m_axi_gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(write_mem_float_128u_U0_m_axi_gmem_WDATA),
    .I_WSTRB(write_mem_float_128u_U0_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(write_mem_float_128u_U0_m_axi_gmem_BREADY)
);

accel_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(entry_proc_U0_start_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .label_r(label_r),
    .label_r_c_din(entry_proc_U0_label_r_c_din),
    .label_r_c_num_data_valid(label_r_c_num_data_valid),
    .label_r_c_fifo_cap(label_r_c_fifo_cap),
    .label_r_c_full_n(label_r_c_full_n),
    .label_r_c_write(entry_proc_U0_label_r_c_write),
    .input_error(input_error),
    .input_error_c_din(entry_proc_U0_input_error_c_din),
    .input_error_c_num_data_valid(input_error_c_num_data_valid),
    .input_error_c_fifo_cap(input_error_c_fifo_cap),
    .input_error_c_full_n(input_error_c_full_n),
    .input_error_c_write(entry_proc_U0_input_error_c_write)
);

accel_save_variables_locally_10u_128u_s save_variables_locally_10u_128u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(save_variables_locally_10u_128u_U0_ap_start),
    .ap_done(save_variables_locally_10u_128u_U0_ap_done),
    .ap_continue(save_variables_locally_10u_128u_U0_ap_continue),
    .ap_idle(save_variables_locally_10u_128u_U0_ap_idle),
    .ap_ready(save_variables_locally_10u_128u_U0_ap_ready),
    .m_axi_gmem_AWVALID(save_variables_locally_10u_128u_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(save_variables_locally_10u_128u_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(save_variables_locally_10u_128u_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(save_variables_locally_10u_128u_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(save_variables_locally_10u_128u_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(save_variables_locally_10u_128u_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(save_variables_locally_10u_128u_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(save_variables_locally_10u_128u_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(save_variables_locally_10u_128u_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(save_variables_locally_10u_128u_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(save_variables_locally_10u_128u_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(save_variables_locally_10u_128u_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(save_variables_locally_10u_128u_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(save_variables_locally_10u_128u_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(save_variables_locally_10u_128u_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(save_variables_locally_10u_128u_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(save_variables_locally_10u_128u_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(save_variables_locally_10u_128u_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(save_variables_locally_10u_128u_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(save_variables_locally_10u_128u_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(save_variables_locally_10u_128u_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(save_variables_locally_10u_128u_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(save_variables_locally_10u_128u_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(save_variables_locally_10u_128u_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(save_variables_locally_10u_128u_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(save_variables_locally_10u_128u_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(save_variables_locally_10u_128u_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(save_variables_locally_10u_128u_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(save_variables_locally_10u_128u_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(save_variables_locally_10u_128u_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(save_variables_locally_10u_128u_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(save_variables_locally_10u_128u_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .gmem_softmax_weights(gmem_softmax_weights),
    .softmax_weights_address0(save_variables_locally_10u_128u_U0_softmax_weights_address0),
    .softmax_weights_ce0(save_variables_locally_10u_128u_U0_softmax_weights_ce0),
    .softmax_weights_we0(save_variables_locally_10u_128u_U0_softmax_weights_we0),
    .softmax_weights_d0(save_variables_locally_10u_128u_U0_softmax_weights_d0),
    .layer_output(layer_output),
    .softmax_f_map_stream14_din(save_variables_locally_10u_128u_U0_softmax_f_map_stream14_din),
    .softmax_f_map_stream14_num_data_valid(softmax_f_map_stream_num_data_valid),
    .softmax_f_map_stream14_fifo_cap(softmax_f_map_stream_fifo_cap),
    .softmax_f_map_stream14_full_n(softmax_f_map_stream_full_n),
    .softmax_f_map_stream14_write(save_variables_locally_10u_128u_U0_softmax_f_map_stream14_write)
);

accel_sparce_categorical_cross_entropy_10u_s sparce_categorical_cross_entropy_10u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sparce_categorical_cross_entropy_10u_U0_ap_start),
    .ap_done(sparce_categorical_cross_entropy_10u_U0_ap_done),
    .ap_continue(sparce_categorical_cross_entropy_10u_U0_ap_continue),
    .ap_idle(sparce_categorical_cross_entropy_10u_U0_ap_idle),
    .ap_ready(sparce_categorical_cross_entropy_10u_U0_ap_ready),
    .softmax_f_map_stream14_dout(softmax_f_map_stream_dout),
    .softmax_f_map_stream14_num_data_valid(softmax_f_map_stream_num_data_valid),
    .softmax_f_map_stream14_fifo_cap(softmax_f_map_stream_fifo_cap),
    .softmax_f_map_stream14_empty_n(softmax_f_map_stream_empty_n),
    .softmax_f_map_stream14_read(sparce_categorical_cross_entropy_10u_U0_softmax_f_map_stream14_read),
    .label_r_dout(label_r_c_dout),
    .label_r_num_data_valid(label_r_c_num_data_valid),
    .label_r_fifo_cap(label_r_c_fifo_cap),
    .label_r_empty_n(label_r_c_empty_n),
    .label_r_read(sparce_categorical_cross_entropy_10u_U0_label_r_read),
    .softmax_output_error_stream15_din(sparce_categorical_cross_entropy_10u_U0_softmax_output_error_stream15_din),
    .softmax_output_error_stream15_num_data_valid(softmax_output_error_stream_num_data_valid),
    .softmax_output_error_stream15_fifo_cap(softmax_output_error_stream_fifo_cap),
    .softmax_output_error_stream15_full_n(softmax_output_error_stream_full_n),
    .softmax_output_error_stream15_write(sparce_categorical_cross_entropy_10u_U0_softmax_output_error_stream15_write)
);

accel_softmax_error_propagation_10u_128u_s softmax_error_propagation_10u_128u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(softmax_error_propagation_10u_128u_U0_ap_start),
    .ap_done(softmax_error_propagation_10u_128u_U0_ap_done),
    .ap_continue(softmax_error_propagation_10u_128u_U0_ap_continue),
    .ap_idle(softmax_error_propagation_10u_128u_U0_ap_idle),
    .ap_ready(softmax_error_propagation_10u_128u_U0_ap_ready),
    .softmax_output_error_stream15_dout(softmax_output_error_stream_dout),
    .softmax_output_error_stream15_num_data_valid(softmax_output_error_stream_num_data_valid),
    .softmax_output_error_stream15_fifo_cap(softmax_output_error_stream_fifo_cap),
    .softmax_output_error_stream15_empty_n(softmax_output_error_stream_empty_n),
    .softmax_output_error_stream15_read(softmax_error_propagation_10u_128u_U0_softmax_output_error_stream15_read),
    .weights_address0(softmax_error_propagation_10u_128u_U0_weights_address0),
    .weights_ce0(softmax_error_propagation_10u_128u_U0_weights_ce0),
    .weights_q0(softmax_weights_t_q0),
    .softmax_input_error_stream16_din(softmax_error_propagation_10u_128u_U0_softmax_input_error_stream16_din),
    .softmax_input_error_stream16_num_data_valid(softmax_input_error_stream_num_data_valid),
    .softmax_input_error_stream16_fifo_cap(softmax_input_error_stream_fifo_cap),
    .softmax_input_error_stream16_full_n(softmax_input_error_stream_full_n),
    .softmax_input_error_stream16_write(softmax_error_propagation_10u_128u_U0_softmax_input_error_stream16_write)
);

accel_write_mem_float_128u_s write_mem_float_128u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_mem_float_128u_U0_ap_start),
    .ap_done(write_mem_float_128u_U0_ap_done),
    .ap_continue(write_mem_float_128u_U0_ap_continue),
    .ap_idle(write_mem_float_128u_U0_ap_idle),
    .ap_ready(write_mem_float_128u_U0_ap_ready),
    .softmax_input_error_stream16_dout(softmax_input_error_stream_dout),
    .softmax_input_error_stream16_num_data_valid(softmax_input_error_stream_num_data_valid),
    .softmax_input_error_stream16_fifo_cap(softmax_input_error_stream_fifo_cap),
    .softmax_input_error_stream16_empty_n(softmax_input_error_stream_empty_n),
    .softmax_input_error_stream16_read(write_mem_float_128u_U0_softmax_input_error_stream16_read),
    .m_axi_gmem_AWVALID(write_mem_float_128u_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(write_mem_float_128u_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(write_mem_float_128u_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(write_mem_float_128u_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(write_mem_float_128u_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(write_mem_float_128u_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(write_mem_float_128u_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(write_mem_float_128u_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(write_mem_float_128u_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(write_mem_float_128u_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(write_mem_float_128u_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(write_mem_float_128u_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(write_mem_float_128u_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(write_mem_float_128u_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(write_mem_float_128u_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(write_mem_float_128u_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(write_mem_float_128u_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(write_mem_float_128u_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(write_mem_float_128u_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(write_mem_float_128u_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(write_mem_float_128u_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(write_mem_float_128u_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(write_mem_float_128u_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(write_mem_float_128u_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(write_mem_float_128u_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(write_mem_float_128u_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(write_mem_float_128u_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(write_mem_float_128u_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(write_mem_float_128u_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(write_mem_float_128u_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(write_mem_float_128u_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(512'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(write_mem_float_128u_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(gmem_BRESP),
    .m_axi_gmem_BID(gmem_BID),
    .m_axi_gmem_BUSER(gmem_BUSER),
    .output_r_dout(input_error_c_dout),
    .output_r_num_data_valid(input_error_c_num_data_valid),
    .output_r_fifo_cap(input_error_c_fifo_cap),
    .output_r_empty_n(input_error_c_empty_n),
    .output_r_read(write_mem_float_128u_U0_output_r_read)
);

accel_fifo_w32_d3_S label_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_label_r_c_din),
    .if_full_n(label_r_c_full_n),
    .if_write(entry_proc_U0_label_r_c_write),
    .if_dout(label_r_c_dout),
    .if_num_data_valid(label_r_c_num_data_valid),
    .if_fifo_cap(label_r_c_fifo_cap),
    .if_empty_n(label_r_c_empty_n),
    .if_read(sparce_categorical_cross_entropy_10u_U0_label_r_read)
);

accel_fifo_w64_d5_S input_error_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_input_error_c_din),
    .if_full_n(input_error_c_full_n),
    .if_write(entry_proc_U0_input_error_c_write),
    .if_dout(input_error_c_dout),
    .if_num_data_valid(input_error_c_num_data_valid),
    .if_fifo_cap(input_error_c_fifo_cap),
    .if_empty_n(input_error_c_empty_n),
    .if_read(write_mem_float_128u_U0_output_r_read)
);

accel_fifo_w32_d2_S softmax_f_map_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(save_variables_locally_10u_128u_U0_softmax_f_map_stream14_din),
    .if_full_n(softmax_f_map_stream_full_n),
    .if_write(save_variables_locally_10u_128u_U0_softmax_f_map_stream14_write),
    .if_dout(softmax_f_map_stream_dout),
    .if_num_data_valid(softmax_f_map_stream_num_data_valid),
    .if_fifo_cap(softmax_f_map_stream_fifo_cap),
    .if_empty_n(softmax_f_map_stream_empty_n),
    .if_read(sparce_categorical_cross_entropy_10u_U0_softmax_f_map_stream14_read)
);

accel_fifo_w32_d6_S softmax_output_error_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sparce_categorical_cross_entropy_10u_U0_softmax_output_error_stream15_din),
    .if_full_n(softmax_output_error_stream_full_n),
    .if_write(sparce_categorical_cross_entropy_10u_U0_softmax_output_error_stream15_write),
    .if_dout(softmax_output_error_stream_dout),
    .if_num_data_valid(softmax_output_error_stream_num_data_valid),
    .if_fifo_cap(softmax_output_error_stream_fifo_cap),
    .if_empty_n(softmax_output_error_stream_empty_n),
    .if_read(softmax_error_propagation_10u_128u_U0_softmax_output_error_stream15_read)
);

accel_fifo_w32_d2_S softmax_input_error_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(softmax_error_propagation_10u_128u_U0_softmax_input_error_stream16_din),
    .if_full_n(softmax_input_error_stream_full_n),
    .if_write(softmax_error_propagation_10u_128u_U0_softmax_input_error_stream16_write),
    .if_dout(softmax_input_error_stream_dout),
    .if_num_data_valid(softmax_input_error_stream_num_data_valid),
    .if_fifo_cap(softmax_input_error_stream_fifo_cap),
    .if_empty_n(softmax_input_error_stream_empty_n),
    .if_read(write_mem_float_128u_U0_softmax_input_error_stream16_read)
);

accel_start_for_sparce_categorical_cross_entropy_10u_U0 start_for_sparce_categorical_cross_entropy_10u_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sparce_categorical_cross_entropy_10u_U0_din),
    .if_full_n(start_for_sparce_categorical_cross_entropy_10u_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_sparce_categorical_cross_entropy_10u_U0_dout),
    .if_empty_n(start_for_sparce_categorical_cross_entropy_10u_U0_empty_n),
    .if_read(sparce_categorical_cross_entropy_10u_U0_ap_ready)
);

accel_start_for_write_mem_float_128u_U0 start_for_write_mem_float_128u_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_mem_float_128u_U0_din),
    .if_full_n(start_for_write_mem_float_128u_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_write_mem_float_128u_U0_dout),
    .if_empty_n(start_for_write_mem_float_128u_U0_empty_n),
    .if_read(write_mem_float_128u_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_save_variables_locally_10u_128u_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_save_variables_locally_10u_128u_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_save_variables_locally_10u_128u_U0_ap_ready <= ap_sync_save_variables_locally_10u_128u_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign ap_done = write_mem_float_128u_U0_ap_done;

assign ap_idle = (write_mem_float_128u_U0_ap_idle & sparce_categorical_cross_entropy_10u_U0_ap_idle & softmax_error_propagation_10u_128u_U0_ap_idle & save_variables_locally_10u_128u_U0_ap_idle & (softmax_weights_t_empty_n ^ 1'b1) & entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_save_variables_locally_10u_128u_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign ap_sync_save_variables_locally_10u_128u_U0_ap_ready = (save_variables_locally_10u_128u_U0_ap_ready | ap_sync_reg_save_variables_locally_10u_128u_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign entry_proc_U0_start_full_n = (start_for_write_mem_float_128u_U0_full_n & start_for_sparce_categorical_cross_entropy_10u_U0_full_n);

assign gmem_BID = 1'd0;

assign gmem_BRESP = 2'd0;

assign gmem_BUSER = 1'd0;

assign gmem_RID = 1'd0;

assign gmem_RLAST = 1'b0;

assign gmem_RRESP = 2'd0;

assign gmem_RUSER = 1'd0;

assign save_variables_locally_10u_128u_U0_ap_continue = softmax_weights_i_full_n;

assign save_variables_locally_10u_128u_U0_ap_start = ((ap_sync_reg_save_variables_locally_10u_128u_U0_ap_ready ^ 1'b1) & ap_start);

assign softmax_error_propagation_10u_128u_U0_ap_continue = 1'b1;

assign softmax_error_propagation_10u_128u_U0_ap_start = softmax_weights_t_empty_n;

assign softmax_weights_t_we0 = 1'b0;

assign sparce_categorical_cross_entropy_10u_U0_ap_continue = 1'b1;

assign sparce_categorical_cross_entropy_10u_U0_ap_start = start_for_sparce_categorical_cross_entropy_10u_U0_empty_n;

assign start_for_sparce_categorical_cross_entropy_10u_U0_din = 1'b1;

assign start_for_write_mem_float_128u_U0_din = 1'b1;

assign write_mem_float_128u_U0_ap_continue = ap_continue;

assign write_mem_float_128u_U0_ap_start = start_for_write_mem_float_128u_U0_empty_n;

endmodule //accel
