// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accel_save_variables_locally_10u_128u_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        gmem_softmax_weights,
        softmax_weights_address0,
        softmax_weights_ce0,
        softmax_weights_we0,
        softmax_weights_d0,
        layer_output,
        softmax_f_map_stream14_din,
        softmax_f_map_stream14_num_data_valid,
        softmax_f_map_stream14_fifo_cap,
        softmax_f_map_stream14_full_n,
        softmax_f_map_stream14_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [511:0] m_axi_gmem_WDATA;
output  [63:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [511:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] gmem_softmax_weights;
output  [6:0] softmax_weights_address0;
output   softmax_weights_ce0;
output  [39:0] softmax_weights_we0;
output  [319:0] softmax_weights_d0;
input  [63:0] layer_output;
output  [31:0] softmax_f_map_stream14_din;
input  [1:0] softmax_f_map_stream14_num_data_valid;
input  [1:0] softmax_f_map_stream14_fifo_cap;
input   softmax_f_map_stream14_full_n;
output   softmax_f_map_stream14_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_ARVALID;
reg[63:0] m_axi_gmem_ARADDR;
reg[0:0] m_axi_gmem_ARID;
reg[31:0] m_axi_gmem_ARLEN;
reg[2:0] m_axi_gmem_ARSIZE;
reg[1:0] m_axi_gmem_ARBURST;
reg[1:0] m_axi_gmem_ARLOCK;
reg[3:0] m_axi_gmem_ARCACHE;
reg[2:0] m_axi_gmem_ARPROT;
reg[3:0] m_axi_gmem_ARQOS;
reg[3:0] m_axi_gmem_ARREGION;
reg[0:0] m_axi_gmem_ARUSER;
reg m_axi_gmem_RREADY;
reg softmax_f_map_stream14_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] empty_fu_73_p1;
reg   [5:0] empty_reg_87;
wire    ap_CS_fsm_state2;
wire   [5:0] trunc_ln174_fu_78_p1;
reg   [5:0] trunc_ln174_reg_97;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_done;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_idle;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_ready;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWVALID;
wire   [63:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWADDR;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWID;
wire   [31:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWLEN;
wire   [2:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWSIZE;
wire   [1:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWBURST;
wire   [1:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWLOCK;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWCACHE;
wire   [2:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWPROT;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWQOS;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWREGION;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWUSER;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WVALID;
wire   [511:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WDATA;
wire   [63:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WSTRB;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WLAST;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WID;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WUSER;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARVALID;
wire   [63:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARADDR;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARID;
wire   [31:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARLEN;
wire   [2:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARSIZE;
wire   [1:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARBURST;
wire   [1:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARLOCK;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARCACHE;
wire   [2:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARPROT;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARQOS;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARREGION;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARUSER;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_RREADY;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_BREADY;
wire   [6:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_address0;
wire    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_ce0;
wire   [39:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_we0;
wire   [319:0] grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_d0;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_done;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_idle;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_ready;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWVALID;
wire   [63:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWADDR;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWID;
wire   [31:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWLEN;
wire   [2:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWSIZE;
wire   [1:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWBURST;
wire   [1:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWLOCK;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWCACHE;
wire   [2:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWPROT;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWQOS;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWREGION;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWUSER;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WVALID;
wire   [511:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WDATA;
wire   [63:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WSTRB;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WLAST;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WID;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WUSER;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARVALID;
wire   [63:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARADDR;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARID;
wire   [31:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARLEN;
wire   [2:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARSIZE;
wire   [1:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARBURST;
wire   [1:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARLOCK;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARCACHE;
wire   [2:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARPROT;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARQOS;
wire   [3:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARREGION;
wire   [0:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARUSER;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_RREADY;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_BREADY;
wire   [31:0] grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_softmax_f_map_stream14_din;
wire    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_softmax_f_map_stream14_write;
reg    grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start_reg;
reg    ap_block_state1_ignore_call6;
reg    grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    ap_block_state1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start_reg = 1'b0;
#0 grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start_reg = 1'b0;
end

accel_save_variables_locally_10u_128u_Pipeline_save_weights_L grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start),
    .ap_done(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_done),
    .ap_idle(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_idle),
    .ap_ready(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_ready),
    .m_axi_gmem_AWVALID(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RFIFONUM(m_axi_gmem_RFIFONUM),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .softmax_weights_address0(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_address0),
    .softmax_weights_ce0(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_ce0),
    .softmax_weights_we0(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_we0),
    .softmax_weights_d0(grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_d0),
    .gmem_softmax_weights(gmem_softmax_weights),
    .gmem_softmax_weights_cast(empty_reg_87)
);

accel_save_variables_locally_10u_128u_Pipeline_stream_input grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start),
    .ap_done(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_done),
    .ap_idle(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_idle),
    .ap_ready(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_ready),
    .m_axi_gmem_AWVALID(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RFIFONUM(m_axi_gmem_RFIFONUM),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .softmax_f_map_stream14_din(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_softmax_f_map_stream14_din),
    .softmax_f_map_stream14_num_data_valid(2'd0),
    .softmax_f_map_stream14_fifo_cap(2'd0),
    .softmax_f_map_stream14_full_n(softmax_f_map_stream14_full_n),
    .softmax_f_map_stream14_write(grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_softmax_f_map_stream14_write),
    .layer_output(layer_output),
    .trunc_ln(trunc_ln174_reg_97)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start_reg <= 1'b1;
        end else if ((grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_ready == 1'b1)) begin
            grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start_reg <= 1'b1;
        end else if ((grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_ready == 1'b1)) begin
            grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_87 <= empty_fu_73_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln174_reg_97 <= trunc_ln174_fu_78_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARADDR = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARADDR = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARADDR;
    end else begin
        m_axi_gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARBURST = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARBURST = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARBURST;
    end else begin
        m_axi_gmem_ARBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARCACHE = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARCACHE = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARCACHE;
    end else begin
        m_axi_gmem_ARCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARID = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARID;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARID = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARID;
    end else begin
        m_axi_gmem_ARID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARLEN = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARLEN = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARLEN;
    end else begin
        m_axi_gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARLOCK = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARLOCK = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARLOCK;
    end else begin
        m_axi_gmem_ARLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARPROT = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARPROT = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARPROT;
    end else begin
        m_axi_gmem_ARPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARQOS = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARQOS = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARQOS;
    end else begin
        m_axi_gmem_ARQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARREGION = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARREGION = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARREGION;
    end else begin
        m_axi_gmem_ARREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARSIZE = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARSIZE = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARSIZE;
    end else begin
        m_axi_gmem_ARSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARUSER = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARUSER = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARUSER;
    end else begin
        m_axi_gmem_ARUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_ARVALID = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_ARVALID = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_ARVALID;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_RREADY = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_RREADY = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_m_axi_gmem_RREADY;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        softmax_f_map_stream14_write = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_softmax_f_map_stream14_write;
    end else begin
        softmax_f_map_stream14_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call6 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_fu_73_p1 = gmem_softmax_weights[5:0];

assign grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_ap_start_reg;

assign grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_ap_start_reg;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 512'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 64'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign softmax_f_map_stream14_din = grp_save_variables_locally_10u_128u_Pipeline_stream_input_fu_63_softmax_f_map_stream14_din;

assign softmax_weights_address0 = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_address0;

assign softmax_weights_ce0 = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_ce0;

assign softmax_weights_d0 = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_d0;

assign softmax_weights_we0 = grp_save_variables_locally_10u_128u_Pipeline_save_weights_L_fu_52_softmax_weights_we0;

assign trunc_ln174_fu_78_p1 = layer_output[5:0];

endmodule //accel_save_variables_locally_10u_128u_s
